import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { QuizProvider } from "@/context/QuizContext";

//Global Layout
export const metadata: Metadata = {
  title: "Frontend Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="xl:pt-20 pt-12 pb-4 px-8 md:px-20 xl:px-36 bg-cover bg-center min-h-screen bg-[url('/pattern-background-mobile-light.svg')] 
      md:bg-[url('/pattern-background-tablet-light.svg')] xl:bg-[url('/pattern-background-desktop-light.svg')]
      dark:bg-[url('/pattern-background-mobile-dark.svg')] dark:md:bg-[url('/pattern-background-tablet-dark.svg')]
      dark:xl:bg-[url('/pattern-background-desktop-dark.svg') dark:bg-dark-navy">
        <QuizProvider>
          <Header />
          {children}
        </QuizProvider>
      </body>
    </html>
  );
}
