import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

//Global Layout
export const metadata: Metadata = {
  title: "Frontend Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="pt-10 pb-5 px-8 md:px-20 lg:px-36 bg-cover bg-center min-h-screen bg-[url('/pattern-background-mobile-light.svg')] md:bg-[url('/pattern-background-tablet-light.svg')] xl:bg-[url('/pattern-background-desktop-light.svg')]">
        <Header />
        {children}
      </body>
    </html>
  );
}
